# docker-compose -f postgres.yml up -d
# docker-compose -f postgres.yml down

version: '3.7'

services:

  postgresdb:
    image: postgres:14.2
    container_name: postgres-felipe
    restart: always
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: abc1234
      POSTGRES_DB: FelipeDB
      POSTGRES_INITDB_ARGS: "--data-checksums"
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - postgres-net
  
  pgAdmin:
    image: dpage/pgadmin4:6.7
    container_name: pgadmin4-felipe
    depends_on:
      - postgresdb
    restart: always
    ports:
      - 8099:80
      - 443:443
    environment:
      PGADMIN_DEFAULT_EMAIL: felipe@felipementel.dev.br
      PGADMIN_DEFAULT_PASSWORD: abc1234
      PGADMIN_DISABLE_POSTFIX: "true"
    networks:
      - postgres-net

networks: 
  postgres-net:
    driver: bridge